### ISSUE TITLE
How exactly do I npm start?

### ISSUE THREAD

**Issue by RaiKzZ** [fairnightzz/Discord-Login-Phishing#7]
Hello,
I did everything step by step but when I npm start it does not work for me. Maybe I did the last step wrong? I opened cmd and went to the Root directory (cd C:\Users\Somebody\Desktop\Discord-Login-Phishing-master\Discord-Login-Phishing-master) and then I entered: npm start. Then I got this error message:
![image](https://user-images.githubusercontent.com/91371916/144710035-559eb96b-2759-4029-a95e-0daead1260c0.png)
What did I do wrong? I also have another idea of what I might have done wrong:
I directly replaced the file: src> config > firebase.js with the config settings (Which is located on Firebase). However the syntax of the code is a bit different after I did this.
![image](https://user-images.githubusercontent.com/91371916/144710458-30cc1801-8b2d-49f4-876d-6abece803e1a.png)
pls help

**Comment by fairnightzz** [comment]
This has nothing to do with the project itself. Here are some tips:
1. The error you are getting in the first image is probably due to the `package-lock.json` file being outdated, so removing the `package-lock.json` and the entire `node_modules` folder then running `npm install` would resolve the issue. In the future, I'd recommend searching up the errors online, because these tend to show up a lot!
2. Your firebase config is incorrect, mainly because you aren't exporting any variables. Please refer to Firebase documentation on how you're supposed to use analytics. If you refer to [this](https://github.com/fairnightzz/Discord-Login-Phishing/blob/master/src/config/firebase.js), you are supposed to export firestore in order to perform actions such as adding items.

**Comment by RaiKzZ** [comment]
> This has nothing to do with the project itself. Here are some tips:
> 
> 1. The error you are getting in the first image is probably due to the `package-lock.json` file being outdated, so removing the `package-lock.json` and the entire `node_modules` folder then running `npm install` would resolve the issue. In the future, I'd recommend searching up the errors online, because these tend to show up a lot!
> 2. Your firebase config is incorrect, mainly because you aren't exporting any variables. Please refer to Firebase documentation on how you're supposed to use analytics. If you refer to [this](https://github.com/fairnightzz/Discord-Login-Phishing/blob/master/src/config/firebase.js), you are supposed to export firestore in order to perform actions such as adding items.


Thanks for replying,
I understand what you are saying and I’ve already fixed the config,
I would like to ask if the way I am trying to do npm start is correct (Locating to cd C:\Users\Somebody\Desktop\Discord-Login-Phishing-master\Discord-Login-Phishing-master in cmd and then type in "npm start". That is not the problem and should normally work, right?

**Comment by RaiKzZ** [comment]
> This has nothing to do with the project itself. Here are some tips:
> 
> 1. The error you are getting in the first image is probably due to the `package-lock.json` file being outdated, so removing the `package-lock.json` and the entire `node_modules` folder then running `npm install` would resolve the issue. In the future, I'd recommend searching up the errors online, because these tend to show up a lot!
> 2. Your firebase config is incorrect, mainly because you aren't exporting any variables. Please refer to Firebase documentation on how you're supposed to use analytics. If you refer to [this](https://github.com/fairnightzz/Discord-Login-Phishing/blob/master/src/config/firebase.js), you are supposed to export firestore in order to perform actions such as adding items.

Hey,
Thank you. I managed to run the file now. However I get another error now, this time it has something to do with the code. Can you please tell me how to fix that 
![image](https://user-images.githubusercontent.com/91371916/144718771-5ce1d0e6-0769-44a5-8aba-9042d48e143b.png)

**Comment by fairnightzz** [comment]
Not too sure why you're getting that error, you could remove that file and line 5 in `src/index.js`

**Comment by RaiKzZ** [comment]
> g that error, you cou

Hey,
Thanks for replying. I did what you said and I am still getting a blank localhost page and this time other error messages. Do you have any idea how I could fix them?
![image](https://user-images.githubusercontent.com/91371916/144751218-85830cd8-0631-47a6-8150-d26cd1524e3c.png)
![image](https://user-images.githubusercontent.com/91371916/144751227-f810327d-99c6-4402-8797-9c96ebabb3c9.png)
Thank you

**Comment by fairnightzz** [comment]
You can see the errors in the console, try searching them up and you'll find them yourself. I believe in you!
